version: "3.8"

services:
  app:
    build:
      context: .
    container_name: jenkinsapp
    ports:
      - "5000:3001"
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
    restart: always
